global:
  scrape_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['10.10.10.61:9100']
        labels: {host: k8s-cp}
      - targets: ['10.10.10.62:9100']
        labels: {host: k8s-w1}
      - targets: ['10.10.10.63:9100']
        labels: {host: k8s-w2}
      - targets: ['10.10.10.64:9100']
        labels: {host: jenkins}
      - targets: ['10.10.10.65:9100']
        labels: {host: monitoring}
